# Generated by Django 3.2.7 on 2021-10-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_posts_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delay',
            field=models.DateTimeField(default=None, null=True, verbose_name='Sending time'),
        ),
    ]
