# Generated by Django 3.2.7 on 2021-10-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211004_1754'),
        ('mainapp', '0004_comment_delay'),
    ]

    operations = [
    ]
